language: node_js
node_js:
  - '0.6'
  - '0.8'
  - '0.10'
  - '0.12'
  - '1.8'
  - '2.5'
  - '3.3'
  - '4.8'
  - '5.12'
  - '6.11'
  - '7.10'
  - '8.4'
sudo: false
dist: precise
cache:
  directories:
    - node_modules
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script:
  - "npm run-script lint"
  - "npm test"
after_success:
  npm run coverage
